on:
  push:
    branches:
      - apt-base

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: Branch
        run: echo "Push event on branch: ${{ github.ref }}"

      - name: Get or create tag
        id: get_tag
        run: |
          TAG="apt-base-latest" # Tag aggiornato
          echo "Trying to create/find tag: $TAG"
          if git show-ref --tags $TAG; then
            echo "Tag $TAG found."
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          else
            echo "Tag $TAG not found, creating it."
            git tag $TAG
            echo "tag=$TAG" >> $GITHUB_OUTPUT
          fi
          echo "Tag value: ${{ steps.get_tag.outputs.tag }}"

      - name: Create or update Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          release_name: Release ${{ steps.get_tag.outputs.tag }}
          body: |
            Aggiornamento della release ${TAG}!
          draft: false
          prerelease: false
        if: github.event_name == 'push'

      - name: Debug: Release creation result
        if: steps.create_release.outcome == 'failure'
        run: |
          echo "Release creation failed. Check the logs for details."
          cat $GITHUB_WORKSPACE/.github/workflows/release.yml
          git status
